# Generated by Django 5.2.6 on 2025-09-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGG_APP', '0002_remove_dealership_dealership_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(verbose_name='Марка')),
                ('model', models.CharField(verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('color', models.CharField(verbose_name='Цвет')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
        ),
    ]
