# Generated by Django 5.2.6 on 2025-09-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGG_APP', '0003_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(verbose_name='Имя')),
                ('address', models.CharField(verbose_name='Адрес')),
                ('phone_number', models.CharField(verbose_name='Номер телефона')),
                ('email', models.CharField(verbose_name='Почта')),
            ],
        ),
    ]
