# Generated by Django 5.2.6 on 2025-09-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGG_APP', '0005_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена продажи')),
                ('sale_date', models.DateField(verbose_name='Дата продажи')),
            ],
        ),
    ]
