# Generated by Django 5.2.6 on 2025-09-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealership_id', models.CharField(verbose_name='Автосалон id')),
                ('name', models.CharField(verbose_name='Имя')),
                ('location', models.CharField(verbose_name='Локация')),
            ],
        ),
    ]
