# Generated by Django 5.2.6 on 2025-09-30 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GGG_APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealership',
            name='dealership_id',
        ),
    ]
