# Generated by Django 5.2.6 on 2025-10-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGG_APP', '0006_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
    ]
